version: 2.1

orbs:
  node: circleci/node@5.0

workflows:
  main:
    jobs:
      - build
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - deb-publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install --yes \
              dpkg \
              eu-strip \
              fakeroot \
              flatpak \
              flatpak-builder
      - node/install-packages
      - run:
          name: "Build"
          command: |
            npm run make -- --arch=x64,arm64
      - store_artifacts:
          path: out/make
  deb-publish:
    docker:
      - image: cimg/base:2022.11
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run: |
          echo 'pkg.atl.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE16slz1okRPeUhxIpzBCn9rHqjk51ylxEYlYXvblswcxOQ0rPyAX6N8Bd2pnsh99xce/jaX2KJHPLPCc+zAXTg= root@li361-16' >> ~/.ssh/known_hosts
      - run: |
          ssh pkg@pkg.atl.revidian.net "mkdir ~/incoming/arc-${CIRCLE_TAG}"
          scp ./dist/*.deb pkg@pkg.atl.revidian.net:incoming/arc-${CIRCLE_TAG}/

          # Ubuntu 20.04 Focal
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-focal-hubci ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-focal-hubci-arc-${CIRCLE_TAG} from repo ftech-ubuntu-focal-hubci"
          ssh pkg@pkg.atl.revidian.net "aptly publish snapshot ftech-ubuntu-focal-hubci-arc-${CIRCLE_HUB} filesystem:ftech:/ubuntu"

          # Ubuntu 21.10 Impish
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-impish-hubci ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-impish-hubci-arc-${CIRCLE_TAG} from repo ftech-ubuntu-impish-hubci"
          ssh pkg@pkg.atl.revidian.net "aptly publish snapshot ftech-ubuntu-impish-hubci-arc-${CIRCLE_HUB} filesystem:ftech:/ubuntu"

          ssh pkg@pkg.atl.revidian.net "rm -r ~/incoming/arc-${CIRCLE_TAG}"
