name: pocket-casts
base: core24
version: '0.11.1'
summary: "The Pocket Casts webapp, packaged for the desktop."
description: |
  Pocket Casts is one of the best podcast / podcatchers out there. This is
  their webapp packaged as a desktop app. The actual webapp itself is the 
  official code from Pocket Casts/NPR. This snap was packaged by Ricardo N 
  Feliciano (FelicianoTech).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

parts:
  pocket-casts:
    plugin: dump
    source:
      - on amd64: "https://github.com/FelicianoTech/pocket-casts-desktop-app/releases/download/v$SNAPCRAFT_PROJECT_VERSION/pocket-casts_$SNAPCRAFT_PROJECT_VERSION_amd64.deb"
      - on arm64: "https://github.com/FelicianoTech/pocket-casts-desktop-app/releases/download/v$SNAPCRAFT_PROJECT_VERSION/pocket-casts_$SNAPCRAFT_PROJECT_VERSION_arm64.deb"
      # Debug
      #- on amd64: "./out/make/deb/x64/pocket-casts_0.10.1_amd64.deb"
    source-type: deb
    stage-packages:
      - alsa-utils
      - glib-networking
      - libasound2
      - libasound2-plugins
      - libgbm1
      - libgtk-3-0
      - libnss3
      - libproxy1v5
    override-build: |
      craftctl default
      sed -i 's|Icon=pocket-casts|Icon=usr/share/pixmaps/pocket-casts.png|' $CRAFT_PART_INSTALL/usr/share/applications/pocket-casts.desktop
    prime:
      - -usr/lib/pocket-casts/chrome-sandbox

apps:
  pocket-casts:
    command: usr/bin/pocket-casts --no-sandbox
    desktop: usr/share/applications/pocket-casts.desktop
    extensions: [gnome]
    plugs:
      - browser-support
      - network
      - desktop
      - wayland
      - audio-playback
      - alsa
